Login completed
KryssNa/TripDash pull request #14
Opened 2023-06-16 02:30 UTC by Libanad

2023-06-18 03:13 UTC, KryssNa requested changes
filename pattern doesnt math

LoginScreen.dart 

dont commit whath you make changes in android  like you have changed local.properties

2023-06-19 13:18 UTC, KryssNa approved these changes
Will be solved in main branch

2023-06-19 13:19 UTC, kingdemon24 approved these changes

2023-06-19 13:35 UTC, haxor09alert approved these changes

2023-06-24 03:49 UTC, closed without merging